export const ErrorCode = {
  COLLECTION_DELETE_BLOCKED_RUNNING: 1101,
  COLLECTION_START_DATE_IN_PAST: 1102,
  COLLECTION_UPDATE_FIELD_BLOCKED_RUNNING: 1103,
  COLLECTION_UPDATE_BLOCKED_ENDED: 1104,
  COLLECTION_ASSIGN_PRODUCTS_BLOCKED_ENDED: 1105,
  PRODUCT_COLLECTION_ENDED: 1212,
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
