export const OrderErrorCode = {
  ORDER_NOT_FOUND: 1801,
  ORDER_INVALID_STATUS_TRANSITION: 1802,
  ORDER_CANCEL_REASON_REQUIRED: 1803,
  ORDER_COMPLETE_REQUIRES_PAYMENT: 1804,
  ORDER_NOT_BANK_TRANSFER: 1805,
  ORDER_ALREADY_PAID: 1806,
  ORDER_CANCELLED_CANNOT_PAY: 1807,
} as const;
