export const UploadErrorCode = {
  UPLOAD_INVALID_PUBLIC_ID: 1901,
  UPLOAD_IMAGE_FILE_REQUIRED: 1902,
  UPLOAD_VIDEO_FILE_REQUIRED: 1903,
  UPLOAD_IMAGE_INVALID_TYPE: 1904,
  UPLOAD_VIDEO_INVALID_TYPE: 1905,
} as const;
