export const VoucherErrorCode = {
  VOUCHER_NOT_FOUND: 2101,
  VOUCHER_CODE_DUPLICATE: 2102,
  VOUCHER_INVALID_DISCOUNT_VALUE: 2103,
  VOUCHER_MAX_DISCOUNT_NOT_APPLICABLE: 2104,
  VOUCHER_HAS_BEEN_USED: 2105,
} as const;
